[package]
name = "eta-core"
version = "0.1.0"
edition = "2021"
license = "BSD-2-Clause"
license-file = "LICENSE"
authors = ["Hans S. <hans@0x8.io>"]
repository = "https://github.com/DaBigBlob/eta-core"

[dependencies]
hashbrown = { version = "0.16.1", default-features = false, features = ["alloc", "default-hasher", "inline-more"] }
